const astitva_db = [
  {
    "id": "T1",
    "name": "Mahalakshmi",
    "name_te": "మహాలక్ష్మి",
    "name_hi": "महालक्ष्मी",
    "category": "Social",
    "priority": "high",
    "target_keywords": ["woman", "female", "wife", "mother", "mahila", "గృహిణి", "అమ్మ", "household"],
    "benefit": "₹2,500/mo + Free Bus + ₹500 Gas",
    "benefit_te": "నెలకు ₹2,500 + ఉచిత బస్సు ప్రయాణం + ₹500 గ్యాస్ సిలిండర్",
    "benefit_hi": "₹2,500/माह + मुफ्त बस यात्रा + ₹500 गैस सिलेंडर",
    "docs": ["Aadhaar", "White Ration Card", "Gas Receipt"],
    "docs_te": ["ఆధార్ కార్డు", "తెల్ల రేషన్ కార్డు", "గ్యాస్ రసీదు"],
    "docs_hi": ["आधार कार्ड", "सफेद राशन कार्ड", "गैस रसीद"],
    "apply_at": "Grama Sachivalayam or Praja Palana center",
    "apply_at_te": "గ్రామ సచివాలయం లేదా ప్రజా పాలన కేంద్రం",
    "apply_at_hi": "ग्राम सचिवालय या प्रजा पालन केंद्र",
    "map_search": "Grama Sachivalayam near me",
    "missing_doc_help_te": "రేషన్ కార్డు లేకపోతే సివిల్ సప్లైస్ ఆఫీస్ కి వెళ్ళండి.",
    "missing_doc_help_hi": "राशन कार्ड न होने पर नागरिक आपूर्ति कार्यालय जाएं।",
    "icon": "wc",
    "eligibility_ineligible": "Government employees, Husband files income tax or GST returns",
    "fine_print": "Bus travel is free for ALL women — no conditions. Only 1 woman per family gets cash benefit."
  },
  {
    "id": "T2",
    "name": "Rythu Bharosa",
    "name_te": "రైతు భరోసా",
    "name_hi": "రైతు భరోసా",
    "category": "Agriculture",
    "priority": "high",
    "target_keywords": ["farmer", "land", "agriculture", "రైతు", "వ్యవసాయం", "పంట", "kisaan"],
    "benefit": "₹12,000/acre/year",
    "benefit_te": "ఎకరాకు ఏడాదికి ₹12,000",
    "benefit_hi": "प्रति एकड़ प्रति वर्ष ₹12,000",
    "docs": ["Pattadar Passbook", "Aadhaar", "Bhu Bharati Card"],
    "docs_te": ["పట్టాదార్ పాస్బుక్", "ఆధార్ కార్డు", "భూ భారతి కార్డు"],
    "docs_hi": ["पट्टादार पासबुक", "आधार कार्ड", "भू भारती कार्ड"],
    "apply_at": "Agriculture Extension Officer (AEO)",
    "apply_at_te": "వ్యవసాయ విస్తరణ అధికారి (AEO)",
    "apply_at_hi": "कृषि विस्तार अधिकारी (AEO)",
    "map_search": "Agriculture office near me",
    "missing_doc_help_te": "పాస్బుక్ కోసం రెవెన్యూ ఆఫీస్ కి వెళ్ళండి.",
    "missing_doc_help_hi": "पासबुक के लिए राजस्व कार्यालय जाएं।",
    "icon": "agriculture",
    "eligibility_ineligible": "Farmers with non-cultivable land (mining, industrial, real estate land)",
    "fine_print": "Includes tenant farmers too. ₹6,000 paid twice a year (Kharif + Rabi seasons)."
  },
  {
    "id": "T3",
    "name": "Cheyutha Pension",
    "name_te": "చేయూత పెన్షన్",
    "name_hi": "चेयुथा पेंशन",
    "category": "Pension",
    "priority": "high",
    "target_keywords": ["pension", "old age", "widow", "disabled", "ముసలివారు", "విధవ", "పెన్షన్"],
    "benefit": "₹4,000 - ₹6,000/month",
    "benefit_te": "నెలకు ₹4,000 నుండి ₹6,000",
    "benefit_hi": "₹4,000 - ₹6,000 प्रति माह",
    "docs": ["Aadhaar", "Age Proof", "White Ration Card", "SADAREM Cert"],
    "docs_te": ["ఆధార్ కార్డు", "వయస్సు ధృవీకరణ", "తెల్ల రేషన్ కార్డు", "సదరం సర్టిఫికేట్"],
    "docs_hi": ["आधार कार्ड", "आयु प्रमाण", "सफेद राशन कार्ड", "सदरम प्रमाणपत्र"],
    "apply_at": "Grama Sachivalayam",
    "apply_at_te": "గ్రామ సచివాలయం",
    "apply_at_hi": "ग्राम सचिवालय",
    "map_search": "Grama Sachivalayam near me",
    "missing_doc_help_te": "సదరం సర్టిఫికేట్ కోసం ప్రభుత్వ ఆసుపత్రికి వెళ్ళండి.",
    "missing_doc_help_hi": "सदरम प्रमाणपत्र के लिए सरकारी अस्पताल जाएं।",
    "icon": "elderly",
    "eligibility_ineligible": "People already getting another government pension, people with regular income source",
    "fine_print": "Amount increased from ₹2,016 to ₹4,000. Disabled people get ₹6,000."
  },
  {
    "id": "T4",
    "name": "Indiramma Indlu",
    "name_te": "ఇందిరమ్మ ఇండ్లు",
    "name_hi": "इंदिरम्मा इडलू",
    "category": "Housing",
    "priority": "high",
    "target_keywords": ["house", "home", "construction", "ఇల్లు", "నిర్మాణం", "makaan"],
    "benefit": "₹5 Lakh for house construction",
    "benefit_te": "ఇంటి నిర్మాణం కోసం ₹5 లక్షలు",
    "benefit_hi": "घर निर्माण के लिए ₹5 लाख",
    "docs": ["Income Certificate", "White Ration Card", "Aadhaar"],
    "docs_te": ["ఆదాయ ధృవీకరణ", "తెల్ల రేషన్ కార్డు", "ఆధార్ కార్డు"],
    "docs_hi": ["आय प्रमाण पत्र", "सफेद राशन कार्ड", "आधार कार्ड"],
    "apply_at": "Gram Panchayat or Praja Palana",
    "apply_at_te": "గ్రామ పంచాయతీ లేదా ప్రజా పాలన",
    "apply_at_hi": "ग्राम पंचायत या प्रजा पालन",
    "map_search": "Gram Panchayat office near me",
    "missing_doc_help_te": "ఆదాయ ధృవీకరణ పత్రం కోసం మీసేవ కి వెళ్ళండి.",
    "missing_doc_help_hi": "आय प्रमाण पत्र के लिए मीसेवा जाएं।",
    "icon": "home",
    "eligibility_ineligible": "People who already own a pucca house in Telangana, income above ₹1.5 lakh/year",
    "fine_print": "SC/ST families get ₹6 lakh (not ₹5 lakh). General category gets ₹5 lakh."
  },
  {
    "id": "T5",
    "name": "Aarogyasri",
    "name_te": "ఆరోగ్యశ్రీ",
    "name_hi": "आरोग्यश्री",
    "category": "Health",
    "priority": "high",
    "target_keywords": ["health", "hospital", "surgery", "treatment", "ఆరోగ్యం", "వైద్యం", "ఆసుపత్రి"],
    "benefit": "Free treatment up to ₹10 Lakh/year",
    "benefit_te": "ఏడాదికి ₹10 లక్షల వరకు ఉచిత వైద్యం",
    "benefit_hi": "प्रति वर्ष ₹10 लाख तक मुफ्त इलाज",
    "docs": ["White Ration Card", "Aadhaar"],
    "docs_te": ["తెల్ల రేషన్ కార్డు", "ఆధార్ కార్డు"],
    "docs_hi": ["सफेद राशन कार्ड", "आधार कार्ड"],
    "apply_at": "MeeSeva for Health Card",
    "apply_at_te": "ఆరోగ్యశ్రీ కార్డు కోసం మీసేవ",
    "apply_at_hi": "आरोग्यश्री कार्ड के लिए मीसेवा",
    "map_search": "MeeSeva near me",
    "missing_doc_help_te": "మీ దగ్గర రేషన్ కార్డు ఉంటే నేరుగా ఆసుపత్రికి వెళ్ళవచ్చు.",
    "missing_doc_help_hi": "यदि आपके पास राशन कार्ड है तो आप सीधे अस्पताल जा सकते हैं।",
    "icon": "medical_services",
    "eligibility_ineligible": "Govt employees, private insurance holders, income above ₹5 lakh/year",
    "fine_print": "Get health card at MeeSeva first. Treatment only at empanelled hospitals. Covers 1,835 treatments."
  },
  {
    "id": "T6",
    "name": "Kalyana Lakshmi",
    "name_te": "కల్యాణ లక్ష్మి",
    "name_hi": "कल्याण लक्ष्मी",
    "category": "Social",
    "priority": "medium",
    "target_keywords": ["marriage", "wedding", "bride", "పెళ్లి", "వివాహం", "shaadi"],
    "benefit": "₹1,00,116 + 10g Gold",
    "benefit_te": "₹1,00,116 + 10 గ్రాముల బంగారం",
    "benefit_hi": "₹1,00,116 + 10 ग्राम सोना",
    "docs": ["Bride Aadhaar", "Income Cert", "Marriage Cert"],
    "docs_te": ["వధువు ఆధార్", "ఆదాయ ధృవీకరణ", "పెళ్లి పత్రిక"],
    "docs_hi": ["दुल्हन का आधार", "आय प्रमाण", "शादी का कार्ड"],
    "apply_at": "MeeSeva (15 days before wedding)",
    "apply_at_te": "మీసేవ (పెళ్లికి 15 రోజుల ముందు)",
    "apply_at_hi": "मीसेवा (शादी से 15 दिन पहले)",
    "map_search": "MeeSeva near me",
    "missing_doc_help_te": "వయస్సు ధృవీకరణ కోసం స్కూల్ సర్టిఫికేట్ లేదా బర్త్ సర్టిఫికేట్ ఉండాలి.",
    "missing_doc_help_hi": "आयु प्रमाण के लिए स्कूल प्रमाण पत्र या जन्म प्रमाण पत्र होना चाहिए।",
    "icon": "celebration",
    "eligibility_ineligible": "Families with income above ₹2 lakh/year, bride below 18 years",
    "fine_print": "Two separate schemes — Kalyana Lakshmi (Hindu SC/ST/BC) and Shaadi Mubarak (Minorities)."
  },
  {
    "id": "T7",
    "name": "Double Bedroom (2BHK)",
    "name_te": "డబుల్ బెడ్ రూమ్ ఇండ్లు",
    "name_hi": "डबल बेडरूम हाउस",
    "category": "Housing",
    "priority": "medium",
    "target_keywords": ["2bhk", "house", "homeless", "ఇల్లు", "మకాన్"],
    "benefit": "Free ready-built 2BHK house",
    "benefit_te": "ఉచితంగా నిర్మించిన డబుల్ బెడ్ రూమ్ ఇల్లు",
    "benefit_hi": "मुफ्त निर्मित डबल बेडरूम घर",
    "docs": ["BPL Card", "Aadhaar"],
    "docs_te": ["బి.పి.ఎల్ కార్డు", "ఆధార్ కార్డు"],
    "docs_hi": ["बीपीएल कार्ड", "आधार कार्ड"],
    "apply_at": "Gram Panchayat",
    "apply_at_te": "గ్రామ పంచాయతీ",
    "apply_at_hi": "ग्राम पंचायत",
    "map_search": "Gram Panchayat office near me",
    "missing_doc_help_te": "మీకు సొంత ఇల్లు లేదని ధృవీకరించే పత్రం ఉండాలి.",
    "missing_doc_help_hi": "आपके पास यह साबित करने के लिए दस्तावेज होना चाहिए कि आपका अपना घर नहीं है।",
    "icon": "apartment",
    "eligibility_ineligible": "People who already own any house or land, non-BPL families",
    "fine_print": "Different from Indiramma Indlu — 2BHK is a ready house, Indiramma Indlu is money to build."
  },
  {
    "id": "T8",
    "name": "Rythu Bima",
    "name_te": "రైతు బీమా",
    "name_hi": "రైతు బీమా",
    "category": "Agriculture",
    "priority": "medium",
    "target_keywords": ["insurance", "farmer death", "బీమా", "రైతు మరణం", "kisaan bima"],
    "benefit": "₹5L insurance for nominee",
    "benefit_te": "నామినీకి ₹5 లక్షల బీమా",
    "benefit_hi": "नामिनी के लिए ₹5 लाख का बीमा",
    "docs": ["Pattadar Passbook"],
    "docs_te": ["పట్టాదార్ పాస్బుక్"],
    "docs_hi": ["पट्टादार पासबुक"],
    "apply_at": "AEO (Auto-enrolled)",
    "apply_at_te": "వ్యవసాయ విస్తరణ అధికారి (ఆటోమేటిక్)",
    "apply_at_hi": "एईओ (स्वचालित नामांकन)",
    "map_search": "Agriculture office near me",
    "missing_doc_help_te": "రైతు చనిపోయిన 10 రోజుల్లోపు ఏ.ఈ.ఓ కి సమాచారం ఇవ్వాలి.",
    "missing_doc_help_hi": "किसान की मृत्यु के 10 दिनों के भीतर एईओ को सूचित किया जाना चाहिए।",
    "icon": "security",
    "eligibility_ineligible": "Farmers below 18 or above 59 years of age",
    "fine_print": "Govt pays premium. Covers natural and accidental death. Money reaches nominee within 10 days."
  },
  {
    "id": "T9",
    "name": "Indiramma Bheema",
    "name_te": "ఇందిరమ్మ కుటుంబ బీమా",
    "name_hi": "इंदिरम्मा बीमा",
    "category": "Social",
    "priority": "medium",
    "target_keywords": ["life insurance", "family", "బీమా", "కుటుంబం"],
    "benefit": "₹5 Lakh Life Insurance",
    "benefit_te": "కుటుంబానికి ₹5 లక్షల జీవిత బీమా",
    "benefit_hi": "परिवार के लिए ₹5 लाख का जीवन बीमा",
    "docs": ["White Ration Card", "Aadhaar"],
    "docs_te": ["తెల్ల రేషన్ కార్డు", "ఆధార్ కార్డు"],
    "docs_hi": ["सफेद राशन कार्ड", "आधार कार्ड"],
    "apply_at": "Starts June 2026",
    "apply_at_te": "జూన్ 2026 నుండి ప్రారంభం",
    "apply_at_hi": "जून 2026 से शुरू",
    "map_search": "Praja Palana center near me",
    "missing_doc_help_te": "రేషన్ కార్డు తప్పనిసరి. కొత్త రేషన్ కార్డుల కోసం వేచి చూడండి.",
    "missing_doc_help_hi": "राशन कार्ड अनिवार्य है। नए राशन कार्ड के लिए प्रतीक्षा करें।",
    "icon": "family_restroom",
    "eligibility_ineligible": "Families without a white ration card",
    "fine_print": "Starts June 2, 2026. Covers 1.15 crore families. Application process not yet announced."
  },
  {
    "id": "T10",
    "name": "Paddy Bonus",
    "name_te": "వరి బోనస్ (సన్న బియ్యం)",
    "name_hi": "धान बोनस",
    "category": "Agriculture",
    "priority": "medium",
    "target_keywords": ["rice", "paddy", "bonus", "వరి", "ధాన్యం", "బోనస్"],
    "benefit": "₹500/quintal extra bonus",
    "benefit_te": "క్వింటాల్కు ₹500 అదనపు బోనస్",
    "benefit_hi": "₹500 प्रति क्विंटल अतिरिक्त बोनस",
    "docs": ["Farmer ID", "Paddy Sale Receipt"],
    "docs_te": ["రైతు గుర్తింపు కార్డు", "ధాన్యం అమ్మకం రశీదు"],
    "docs_hi": ["किसान आईडी", "धान बिक्री रसीद"],
    "apply_at": "Govt Procurement Centers",
    "apply_at_te": "ప్రభుత్వ ధాన్యం కొనుగోలు కేంద్రాలు",
    "apply_at_hi": "सरकारी खरीद केंद्र",
    "map_search": "Paddy procurement center near me",
    "missing_doc_help_te": "సన్న రకం వరి పండించిన రైతులకు మాత్రమే ఈ బోనస్ అందుతుంది.",
    "missing_doc_help_hi": "यह बोनस केवल बारीक किस्म का धान उगाने वाले किसानों के लिए है।",
    "icon": "paid",
    "eligibility_ineligible": "Farmers growing coarse rice, or selling to private buyers",
    "fine_print": "Only for 33 notified fine rice varieties. Bonus directly credited to bank account."
  },
  {
    "id": "T11",
    "name": "Gruha Jyothi",
    "name_te": "గృహ జ్యోతి",
    "name_hi": "गृह ज्योति",
    "category": "Utility",
    "priority": "high",
    "target_keywords": ["current", "electricity", "bill", "కరెంటు", "విద్యుత్", "bijli"],
    "benefit": "200 units free electricity/month",
    "benefit_te": "నెలకి 200 రెండు వందల (rendu vandala) యూనిట్ల ఉచిత కరెంటు",
    "benefit_hi": "हर महीने 200 दो सौ (do sau) यूनिट मुफ्त बिजली",
    "docs": ["Electricity Bill", "Aadhaar", "Ration Card"],
    "docs_te": ["కరెంటు బిల్లు", "ఆధార్ కార్డు", "రేషన్ కార్డు"],
    "docs_hi": ["बिजली बिल", "आधार कार्ड", "राशन कार्ड"],
    "apply_at": "Electricity Board",
    "apply_at_te": "విద్యుత్ కార్యాలయం",
    "apply_at_hi": "बिजली बोर्ड",
    "map_search": "Electricity office near me",
    "missing_doc_help_te": "మీ పాత కరెంటు బిల్లు మీద ఉన్న సర్వీస్ నంబర్ చూసుకోండి.",
    "missing_doc_help_hi": "अपने पुराने बिजली बिल पर सेवा संख्या देखें।",
    "icon": "lightbulb",
    "eligibility_ineligible": "Usage above 200 units, commercial connections, no domestic connection",
    "fine_print": "Even 1 unit above 200 means full bill is charged. Only 1 connection per family. Ration card must be Aadhaar-linked."
  },
  {
    "id": "T12",
    "name": "T-Fiber",
    "name_te": "టీ-ఫైబర్",
    "name_hi": "टी-फाइबर",
    "category": "Infrastructure",
    "priority": "low",
    "target_keywords": ["internet", "wifi", "ఇంటర్నెట్", "వైఫై", "net"],
    "benefit": "High-speed internet for rural homes",
    "benefit_te": "గ్రామాల్లో వేగవంతమైన ఇంటర్నెట్ సదుపాయం",
    "benefit_hi": "ग्रामीण घरों के लिए तेज़ इंटरनेट",
    "docs": ["Aadhaar"],
    "docs_te": ["ఆధార్ కార్డు"],
    "docs_hi": ["आधार कार्ड"],
    "apply_at": "Gram Panchayat Office",
    "apply_at_te": "గ్రామ పంచాయతీ కార్యాలయం",
    "apply_at_hi": "ग्राम पंचायत कार्यालय",
    "map_search": "Gram Panchayat near me",
    "missing_doc_help_te": "మరిన్ని వివరాల కోసం పంచాయతీ సెక్రటరీని అడగండి.",
    "missing_doc_help_hi": "अधिक जानकारी के लिए पंचायत सचिव से पूछें।",
    "icon": "router",
    "eligibility_ineligible": "Non-rural households",
    "fine_print": "Aims to provide high-speed internet to every rural household in Telangana."
  },
  {
    "id": "T13",
    "name": "CM Dual-Meal Scheme",
    "name_te": "ముఖ్యమంత్రి అల్పాహార పథకం",
    "name_hi": "मुख्यमंत्री नाश्ता योजना",
    "category": "Education",
    "priority": "medium",
    "target_keywords": ["school food", "breakfast", "milk", "పిల్లల భోజనం", "పాలు"],
    "benefit": "Free breakfast, Milk, and Ragi Malt",
    "benefit_te": "బడి పిల్లలకు ఉచిత అల్పాహారం, పాలు మరియు రాగి మాల్ట్",
    "benefit_hi": "मुफ्त नाश्ता, दूध और रागी माल्ट",
    "docs": ["School ID"],
    "docs_te": ["స్కూల్ గుర్తింపు కార్డు"],
    "docs_hi": ["स्कूल आईडी कार्ड"],
    "apply_at": "Government Schools",
    "apply_at_te": "ప్రభుత్వ పాఠశాలల్లో నేరుగా",
    "apply_at_hi": "सरकारी स्कूल में",
    "map_search": "Government school near me",
    "missing_doc_help_te": "ఇది కేవలం ప్రభుత్వ పాఠశాలల్లో చదివే పిల్లలకు మాత్రమే.",
    "missing_doc_help_hi": "यह केवल सरकारी स्कूलों में पढ़ने वाले बच्चों के लिए है।",
    "icon": "restaurant",
    "eligibility_ineligible": "Private school students, children not enrolled in govt schools",
    "fine_print": "Launching from 2026-27 academic year. Milk 3 days/week + ragi malt 3 days/week."
  },
  {
    "id": "T14",
    "name": "Amma Vodi",
    "name_te": "అమ్మ ఒడి",
    "name_hi": "अम्मा वोडी",
    "category": "Education",
    "priority": "high",
    "target_keywords": ["education money", "mother", "చదువు", "తల్లి", "school"],
    "benefit": "₹15,000/year for education",
    "benefit_te": "పిల్లల చదువు కోసం ఏడాదికి 15,000 పదిహేను వేల (padihenu vela) రూపాయలు",
    "benefit_hi": "शिक्षा के लिए प्रति वर्ष 15,000 पंद्रह हजार (pandrah hazar) रुपये",
    "docs": ["White Ration Card", "Aadhaar", "School Cert"],
    "docs_te": ["తెల్ల రేషన్ కార్డు", "ఆధార్ కార్డు", "స్కూల్ సర్టిఫికేట్"],
    "docs_hi": ["सफेद राशन कार्ड", "आधार कार्ड", "स्कूल प्रमाण पत्र"],
    "apply_at": "Village/Ward Office",
    "apply_at_te": "గ్రామ లేదా వార్డు సచివాలయం",
    "apply_at_hi": "गांव या वार्ड कार्यालय",
    "map_search": "Village office near me",
    "missing_doc_help_te": "తల్లి పేరు మీద తెల్ల రేషన్ కార్డు ఉండాలి.",
    "missing_doc_help_hi": "माता के नाम पर सफेद राशन कार्ड होना चाहिए।",
    "icon": "school",
    "eligibility_ineligible": "Families without white ration card, non-school going children",
    "fine_print": "Assistance for mothers to send their children to school."
  },
  {
    "id": "T15",
    "name": "Indira Soura Giri Jala Vikasam",
    "name_te": "గిరి జల వికాసం",
    "name_hi": "गिरी जल विकास",
    "category": "Agriculture",
    "priority": "medium",
    "target_keywords": ["st farmer", "solar pump", "tribal", "గిరిజన", "సోలార్ పంప్"],
    "benefit": "100% subsidy on solar pumps",
    "benefit_te": "గిరిజన రైతులకు 100 వంద (vanda) శాతం సబ్సిడీతో సోలార్ పంపులు",
    "benefit_hi": "एसटी किसानों के लिए सोलर पंप पर 100 सौ (sau) प्रतिशत सब्सिडी",
    "docs": ["Tribal Certificate", "Aadhaar", "Land Docs"],
    "docs_te": ["కుల ధృవీకరణ పత్రం", "ఆధార్ కార్డు", "పట్టా దార్ పాస్బుక్"],
    "docs_hi": ["जनजाति प्रमाण पत्र", "आधार कार्ड", "भूमि दस्तावेज"],
    "apply_at": "ITDA Office",
    "apply_at_te": "ఐ.టి.డి.ఏ (ITDA) కార్యాలయం",
    "apply_at_hi": "आईटीडीए (ITDA) कार्यालय",
    "map_search": "ITDA office near me",
    "missing_doc_help_te": "కుల ధృవీకరణ పత్రం కోసం తహశీల్దార్ ఆఫీస్ కి వెళ్ళండి.",
    "missing_doc_help_hi": "जाति प्रमाण पत्र के लिए तहसीलदार कार्यालय जाएं।",
    "icon": "solar_power",
    "eligibility_ineligible": "Non-ST families, people without tribal certificate",
    "fine_print": "Provides solar irrigation pumps to ST farmers with 100% subsidy."
  },
  {
    "id": "T16",
    "name": "Nethanna Bima",
    "name_te": "నేతన్న బీమా",
    "name_hi": "नेथन्ना बीमा",
    "category": "Insurance",
    "priority": "medium",
    "target_keywords": ["weaver", "handloom", "నేతన్న", "మగ్గం", "insurance"],
    "benefit": "₹5 Lakh life insurance",
    "benefit_te": "నేత కార్మికుల కుటుంబానికి 5 ఐదు (aidhu) లక్షల రూపాయల బీమా",
    "benefit_hi": "बुनकरों के परिवार के लिए 5 पांच (paanch) लाख रुपये का बीमा",
    "docs": ["Weaver ID Card", "Aadhaar"],
    "docs_te": ["నేతన్న గుర్తింపు కార్డు", "ఆధార్ కార్డు"],
    "docs_hi": ["बुनकर आईडी कार्ड", "आधार कार्ड"],
    "apply_at": "Handloom Department",
    "apply_at_te": "చేనేత శాఖ కార్యాలయం",
    "apply_at_hi": "हथकरघा विभाग",
    "map_search": "Handloom department near me",
    "missing_doc_help_te": "మీరు తప్పనిసరిగా నమోదైన నేత కార్మికులై ఉండాలి.",
    "missing_doc_help_hi": "आपको एक पंजीकृत बुनकर होना चाहिए।",
    "icon": "dry_cleaning",
    "eligibility_ineligible": "Weavers below 18 or above 59, non-registered weavers",
    "fine_print": "Life insurance scheme only. No monthly pension component."
  },
  {
    "id": "T17",
    "name": "Single Women Pension",
    "name_te": "ఒంటరి మహిళా పెన్షన్",
    "name_hi": "एकल महिला पेंशन",
    "category": "Pension",
    "priority": "high",
    "target_keywords": ["single woman", "separated", "ఒంటరి మహిళ", "పెన్షన్"],
    "benefit": "₹4,000/month pension",
    "benefit_te": "ఒంటరి మహిళలకు నెలకు 4,000 నాలుగు వేల (nalugu vela) రూపాయల పెన్షన్",
    "benefit_hi": "एकल महिलाओं के लिए हर महीने 4,000 चार हजार (chaar hazar) रुपये पेंशन",
    "docs": ["Marital Status Cert", "White Ration Card", "Aadhaar"],
    "docs_te": ["మ్యారేజ్ స్టేటస్ సర్టిఫికేట్", "తెల్ల రేషన్ కార్డు", "ఆధార్ కార్డు"],
    "docs_hi": ["वैवाहिक स्थिति प्रमाण पत्र", "सफेद राशन कार्ड", "आधार कार्ड"],
    "apply_at": "Gram Panchayat Office",
    "apply_at_te": "గ్రామ పంచాయతీ కార్యాలయం",
    "apply_at_hi": "ग्राम पंचायत कार्यालय",
    "map_search": "Gram Panchayat near me",
    "missing_doc_help_te": "ఒంటరిగా ఉంటున్నట్టు ధృవీకరణ పత్రం పంచాయతీలో ఇస్తారు.",
    "missing_doc_help_hi": "पंचायत में एकल स्थिति का प्रमाण पत्र दिया जाएगा।",
    "icon": "person_pin",
    "eligibility_ineligible": "Women already getting another pension, income above limit (₹1.5L rural / ₹2L urban)",
    "fine_print": "Married women separated ≥1 year, or unmarried 30+ (rural) / 35+ (urban)."
  },
  {
    "id": "T18",
    "name": "MSME Subsidy",
    "name_te": "పరిశ్రమల సబ్సిడీ",
    "name_hi": "एमएसएमई सब्सिडी",
    "category": "Business",
    "priority": "low",
    "target_keywords": ["business", "factory", "పరిశ్రమ", "వ్యాపారం", "MSME"],
    "benefit": "25% investment subsidy",
    "benefit_te": "పెట్టుబడిపై 25 ఇరవై ఐదు (iravai aidhu) శాతం సబ్సిడీ",
    "benefit_hi": "निवेश पर 25 पच्चीस (pachis) प्रतिशत सब्सिडी",
    "docs": ["Project Report", "Aadhaar", "Business License"],
    "docs_te": ["ప్రాజెక్ట్ రిపోర్ట్", "ఆధార్ కార్డు", "వ్యాపార లైసెన్స్"],
    "docs_hi": ["प्रोजेक्ट रिपोर्ट", "आधार कार्ड", "व्यापार लाइसेंस"],
    "apply_at": "District Industries Centre (DIC)",
    "apply_at_te": "జిల్లా పరిశ్రమల కేంద్రం (DIC)",
    "apply_at_hi": "जिला उद्योग केंद्र (DIC)",
    "map_search": "DIC office near me",
    "missing_doc_help_te": "మీ ప్రాజెక్ట్ రిపోర్ట్ తయారీకి DIC ఆఫీస్ లో సాయం పొందండి.",
    "missing_doc_help_hi": "प्रोजेक्ट रिपोर्ट बनाने के लिए डीआईसी कार्यालय में सहायता लें।",
    "icon": "factory",
    "eligibility_ineligible": "Large enterprises, non-MSME units",
    "fine_print": "Financial assistance for setting up small and medium scale industries."
  },
  {
    "id": "T19",
    "name": "Matsya Bandhu",
    "name_te": "మత్స్య బంధు",
    "name_hi": "मत्स्य बंधु",
    "category": "Fisheries",
    "priority": "medium",
    "target_keywords": ["fisherman", "fish seeds", "జాలరి", "చేపలు"],
    "benefit": "100% subsidy on seeds/equipment",
    "benefit_te": "చేప విత్తనాలు మరియు వలలపై 100 వంద (vanda) శాతం సబ్సిడీ",
    "benefit_hi": "बीज और उपकरणों पर 100 सौ (sau) प्रतिशत सब्सिडी",
    "docs": ["Fishermen ID Card", "Aadhaar"],
    "docs_te": ["జాలరి గుర్తింపు కార్డు", "ఆధార్ కార్డు"],
    "docs_hi": ["मछुआरा आईडी कार्ड", "आधार कार्ड"],
    "apply_at": "Fisheries Department",
    "apply_at_te": "మత్స్య శాఖ కార్యాలయం",
    "apply_at_hi": "मत्स्य विभाग",
    "map_search": "Fisheries office near me",
    "missing_doc_help_te": "మత్స్యకార సహకార సంఘంలో సభ్యత్వం ఉండాలి.",
    "missing_doc_help_hi": "मछुआरा सहकारी समिति की सदस्यता होनी चाहिए।",
    "icon": "phishing",
    "eligibility_ineligible": "Non-licensed fishermen",
    "fine_print": "Provides support during fishing ban periods plus craft and net equipment."
  },
  {
    "id": "T20",
    "name": "CMRF",
    "name_te": "ముఖ్యమంత్రి సహాయ నిధి",
    "name_hi": "मुख्यमंत्री सहायता कोष",
    "category": "Health",
    "priority": "high",
    "target_keywords": ["emergency money", "medical aid", "అత్యవసర చికిత్స", "సాయం"],
    "benefit": "Financial aid for serious illness",
    "benefit_te": "పెద్ద జబ్బుల చికిత్స కోసం ముఖ్యమంత్రి ఆర్థిక సహాయం",
    "benefit_hi": "गंभीर बीमारी के इलाज के लिए मुख्यमंत्री की सहायता",
    "docs": ["Medical Bills", "Income Cert", "Aadhaar", "CM Letter"],
    "docs_te": ["వైద్య బిల్లులు", "ఆదాయ ధృవీకరణ", "ఆధార్ కార్డు", "సి.ఎం కు విన్నపం"],
    "docs_hi": ["मेडिकल बिल", "आय प्रमाण", "आधार कार्ड", "सीएम को पत्र"],
    "apply_at": "CMRF Portal or MLA Office",
    "apply_at_te": "CMRF పోర్టల్ లేదా ఎమ్మెల్యే కార్యాలయం",
    "apply_at_hi": "CMRF पोर्टल या विधायक कार्यालय",
    "map_search": "MLA office near me",
    "missing_doc_help_te": "ఆసుపత్రి నుండి డిశ్చార్జ్ సమ్మరీ మరియు బిల్లులు ఉండాలి.",
    "missing_doc_help_hi": "अस्पताल से डिस्चार्ज समरी और बिल होने चाहिए।",
    "icon": "emergency",
    "eligibility_ineligible": "Income above BPL limit, non-medical emergencies",
    "fine_print": "Financial assistance for surgery/treatment not covered by Aarogyasri."
  },
  {
    "id": "T21",
    "name": "Indira Dairy Subsidy",
    "name_te": "పాడి పశువుల సబ్సిడీ",
    "name_hi": "डेयरी सब्सिडी",
    "category": "Agriculture",
    "priority": "medium",
    "target_keywords": ["buffalo", "cow", "dairy", "గేదెలు", "ఆవులు"],
    "benefit": "70% subsidy on cattle",
    "benefit_te": "పాడి పశువుల కొనుగోలుపై 70 డెబ్బై (debbai) శాతం సబ్సిడీ",
    "benefit_hi": "दुधारू पशुओं की खरीद पर 70 सत्तर (sattar) प्रतिशत सब्सिडी",
    "docs": ["Aadhaar", "SHG ID", "Bank Passbook"],
    "docs_te": ["ఆధార్ కార్డు", "గ్రూపు ID", "బ్యాంక్ పాస్బుక్"],
    "docs_hi": ["आधार कार्ड", "समूह आईडी", "बैंक पासबुक"],
    "apply_at": "Dairy Cooperative Society",
    "apply_at_te": "పాడి రైతు సహకార సంఘం",
    "apply_at_hi": "डेयरी सहकारी समिति",
    "map_search": "Dairy cooperative near me",
    "missing_doc_help_te": "పశువుల షెడ్డు ఉన్నవారికి ప్రాధాన్యత ఉంటుంది.",
    "missing_doc_help_hi": "पशु शेड वालों को प्राथमिकता दी जाएगी।",
    "icon": "pets",
    "eligibility_ineligible": "Non-registered farmers, families already owning large herds",
    "fine_print": "70% subsidy on purchase of buffaloes and cows. Priority for families with no cattle."
  },
  {
    "id": "T22",
    "name": "Sheep Distribution",
    "name_te": "గొర్రెల పంపిణీ పథకం",
    "name_hi": "भेड़ वितरण योजना",
    "category": "Agriculture",
    "priority": "medium",
    "target_keywords": ["sheep", "shepherd", "livestock", "గొర్రెలు", "కురుమ"],
    "benefit": "75% subsidy on sheep purchase",
    "benefit_te": "గొర్రెల కొనుగోలుపై 75 డెబ్బై ఐదు (debbai aidhu) శాతం సబ్సిడీ",
    "benefit_hi": "भेड़ की खरीद पर 75 पचहत्तर (pachhattar) प्रतिशत सब्सिडी",
    "docs": ["Shepherd ID", "Aadhaar"],
    "docs_te": ["గొర్రెల కాపరి గుర్తింపు కార్డు", "ఆధార్ కార్డు"],
    "docs_hi": ["चरवाहा आईडी", "आधार कार्ड"],
    "apply_at": "Animal Husbandry Department",
    "apply_at_te": "పశుసంవర్ధక శాఖ కార్యాలయం",
    "apply_at_hi": "पशुपालन विभाग",
    "map_search": "Animal husbandry office near me",
    "missing_doc_help_te": "గొర్రెల కాపరి సహకార సంఘంలో సభ్యుడిగా ఉండాలి.",
    "missing_doc_help_hi": "भेड़ चरवाहा सहकारी समिति का सदस्य होना चाहिए।",
    "icon": "goat",
    "eligibility_ineligible": "Non-shepherd community families",
    "fine_print": "Financial support for the Kuruma/Yadava shepherd communities."
  },
  {
    "id": "C1",
    "name": "Ayushman Bharat",
    "name_te": "ఆయుష్మాన్ భారత్",
    "name_hi": "आयुष्मान भारत",
    "category": "Health",
    "priority": "high",
    "target_keywords": ["hospital", "health insurance", "70 plus", "ఆరోగ్యం", "ఆసుపత్రి", "doctor"],
    "benefit": "₹5L hospital coverage (Universal for 70+)",
    "benefit_te": "హాస్పిటల్ ఖర్చుల కోసం 5 ఐదు (aidhu) లక్షల రూపాయల వరకు ఉచిత భీమా",
    "benefit_hi": "अस्पताल के खर्च के लिए 5 पांच (paanch) लाख रुपये तक का मुफ्त बीमा",
    "docs": ["Aadhaar"],
    "docs_te": ["ఆధార్ కార్డు"],
    "docs_hi": ["आधार कार्ड"],
    "apply_at": "Nearest CSC Center or Empanelled Hospital",
    "apply_at_te": "దగ్గరలోని మీసేవ కేంద్రం లేదా ప్రభుత్వ ఆసుపత్రి",
    "apply_at_hi": "नजदीकी सीएससी केंद्र या सरकारी अस्पताल",
    "map_search": "CSC center near me",
    "missing_doc_help_te": "70 ఏళ్ళ పైబడిన అందరికీ ఇది వర్తిస్తుంది, ఆదాయంతో సంబంధం లేదు.",
    "missing_doc_help_hi": "यह 70 वर्ष से अधिक उम्र के सभी लोगों के लिए है, आय चाहे जो भी हो।",
    "icon": "medical_services",
    "eligibility_ineligible": "Families earning above ₹5 lakh/year, government employees with other health coverage",
    "fine_print": "All senior citizens 70+ get SEPARATE ₹5 lakh cover regardless of income. Works nationwide."
  },
  {
    "id": "C2",
    "name": "PM-KISAN",
    "name_te": "పీఎం కిసాన్",
    "name_hi": "पीएम किसान",
    "category": "Agriculture",
    "priority": "high",
    "target_keywords": ["farmer", "kisan money", "land", "రైతు", "పెట్టుబడి", "kheti"],
    "benefit": "₹6,000/yr in 3 installments",
    "benefit_te": "రైతులకు ఏడాదికి 6 ఆరు (aaru) వేల రూపాయల పెట్టుబడి సాయం",
    "benefit_hi": "किसानों को साल में 6 छह (chheh) हजार रुपये की मदद",
    "docs": ["Land Records", "Aadhaar", "e-KYC"],
    "docs_te": ["పట్టాదార్ పాస్బుక్", "ఆధార్ కార్డు", "ఈ-కేవైసీ"],
    "docs_hi": ["भूमि दस्तावेज", "आधार कार्ड", "ई-केवाईसी"],
    "apply_at": "MeeSeva or CSC Center",
    "apply_at_te": "మీసేవ లేదా సి.ఎస్.సి (CSC) కేంద్రం",
    "apply_at_hi": "मीसेवा या सीएससी केंद्र",
    "map_search": "MeeSeva near me",
    "missing_doc_help_te": "ప్రతి ఏటా మీసేవ కేంద్రంలో ఈ-కేవైసీ (e-KYC) చేయించుకోవడం ముఖ్యం.",
    "missing_doc_help_hi": "हर साल सीएससी केंद्र पर ई-केवाईसी करवाना जरूरी है।",
    "icon": "agriculture",
    "eligibility_ineligible": "Institutional landholders, govt employees, income tax payers, farmers > 2 hectares",
    "fine_print": "Amount is fixed ₹6,000/year in 3 installments of ₹2,000 each. e-KYC mandatory."
  },
  {
    "id": "C3",
    "name": "PM Ujjwala",
    "name_te": "ఉజ్వల యోజన",
    "name_hi": "उज्ज्वला योजना",
    "category": "Utility",
    "priority": "medium",
    "target_keywords": ["gas", "cylinder", "stove", "గ్యాస్", "పొయ్యి", "chulha"],
    "benefit": "Free LPG connection + subsidy",
    "benefit_te": "ఉచిత గ్యాస్ కనెక్షన్ మరియు సబ్సిడీ",
    "benefit_hi": "मुफ्त गैस कनेक्शन और सब्सिडी",
    "docs": ["BPL Card", "Aadhaar"],
    "docs_te": ["తెల్ల రేషన్ కార్డు", "ఆధార్ కార్డు"],
    "docs_hi": ["बीपीएल कार्ड", "आधार कार्ड"],
    "apply_at": "Nearest Gas Dealer",
    "apply_at_te": "దగ్గరలోని గ్యాస్ ఏజెన్సీ",
    "apply_at_hi": "नजदीकी गैस एजेंसी",
    "map_search": "Gas agency near me",
    "missing_doc_help_te": "ఇది కేవలం ఇంట్లో గ్యాస్ కనెక్షన్ లేని పేద మహిళలకు మాత్రమే.",
    "missing_doc_help_hi": "यह केवल उन गरीब महिलाओं के लिए है जिनके पास गैस कनेक्शन नहीं है।",
    "icon": "gas_meter",
    "eligibility_ineligible": "Families with existing LPG connection, non-BPL families",
    "fine_print": "Free connection only — refill cylinders must be paid for. Applicant must be woman 18+."
  },
  {
    "id": "C4",
    "name": "MGNREGA",
    "name_te": "ఉపాధి హామీ పథకం",
    "name_hi": "मनरेगा",
    "category": "Employment",
    "priority": "high",
    "target_keywords": ["work", "100 days", "manual labour", "పని", "కూలి", "rozgar"],
    "benefit": "100 days guaranteed employment",
    "benefit_te": "ఏడాదికి 100 వంద (vanda) రోజుల పని గ్యారెంటీ",
    "benefit_hi": "साल में 100 सौ (sau) दिन के काम की गारंटी",
    "docs": ["Job Card", "Aadhaar", "Bank Account"],
    "docs_te": ["ఉపాధి హామీ కార్డు", "ఆధార్ కార్డు", "బ్యాంక్ ఖాతా"],
    "docs_hi": ["जॉब कार्ड", "आधार कार्ड", "बैंक खाता"],
    "apply_at": "Gram Panchayat",
    "apply_at_te": "గ్రామ పంచాయతీ కార్యాలయం",
    "apply_at_hi": "ग्राम पंचायत कार्यालय",
    "map_search": "Gram Panchayat near me",
    "missing_doc_help_te": "జాబ్ కార్డు కోసం మీ ఊరి పంచాయతీ సెక్రటరీని సంప్రదించండి.",
    "missing_doc_help_hi": "जॉब कार्ड के लिए अपने ग्राम सचिव से मिलें।",
    "icon": "work",
    "eligibility_ineligible": "People from urban areas, minors",
    "fine_print": "Guaranteed 100 days of manual work per year at minimum wage."
  },
  {
    "id": "C5",
    "name": "Sukanya Samriddhi",
    "name_te": "సుకన్య సమృద్ధి యోజన",
    "name_hi": "सुकन्या समृद्धि योजना",
    "category": "Savings",
    "priority": "medium",
    "target_keywords": ["girl child", "savings", "daughter", "ఆడపిల్ల", "పొదుపు", "beti"],
    "benefit": "8.2% interest for girl child",
    "benefit_te": "ఆడపిల్లల పేరు మీద పొదుపు చేస్తే ఎక్కువ వడ్డీ",
    "benefit_hi": "बेटियों के नाम बचत पर सबसे ज्यादा ब्याज",
    "docs": ["Birth Certificate", "Parent Aadhaar"],
    "docs_te": ["పుట్టిన తేదీ ధృవీకరణ", "తల్లిదండ్రుల ఆధార్"],
    "docs_hi": ["जन्म प्रमाण पत्र", "माता-पिता का आधार"],
    "apply_at": "Post Office or Bank",
    "apply_at_te": "పోస్ట్ ఆఫీస్ లేదా బ్యాంకు",
    "apply_at_hi": "डाकघर या बैंक",
    "map_search": "Post office near me",
    "missing_doc_help_te": "పాపకి 10 పది (padi) ఏళ్ల వయస్సు లోపు మాత్రమే ఈ ఖాతా తెరవవచ్చు.",
    "missing_doc_help_hi": "यह खाता बेटी की उम्र 10 दस (das) साल होने से पहले ही खोला जा सकता है।",
    "icon": "savings",
    "eligibility_ineligible": "Girl child above 10 years, more than 2 girls per family (except twins)",
    "fine_print": "Highest interest rate in govt savings. Matures after 21 years. Min deposit ₹250/year."
  },
  {
    "id": "C6",
    "name": "PM Vishwakarma",
    "name_te": "పీఎం విశ్వకర్మ",
    "name_hi": "पीएम विश्वकर्मा",
    "category": "Employment",
    "priority": "medium",
    "target_keywords": ["artisan", "carpenter", "skill", "చేతి వృత్తులు", "శిక్షణ", "karigar"],
    "benefit": "₹3L loan + skill training",
    "benefit_te": "3 మూడు (moodu) లక్షల రుణం మరియు ఉచిత శిక్షణ",
    "benefit_hi": "₹3 लाख ऋण और कौशल प्रशिक्षण",
    "docs": ["Aadhaar", "Skill Proof"],
    "docs_te": ["ఆధార్ కార్డు", "వృత్తి ధృవీకరణ"],
    "docs_hi": ["आधार कार्ड", "कौशल प्रमाण"],
    "apply_at": "CSC Center",
    "apply_at_te": "సి.ఎస్.సి (CSC) కేంద్రం",
    "apply_at_hi": "सीएससी केंद्र",
    "map_search": "CSC center near me",
    "missing_doc_help_te": "కుమ్మరి, వడ్రంగి వంటి 18 రకాల చేతి వృత్తుల వారికి ఇది వర్తిస్తుంది.",
    "missing_doc_help_hi": "यह कुम्हार, बढ़ई जैसे 18 पारंपरिक व्यवसायों के लिए है।",
    "icon": "construction",
    "eligibility_ineligible": "Non-artisans, govt employees, those who took similar loans recently",
    "fine_print": "Includes toolkit incentive of ₹15,000 and stipend during training."
  },
  {
    "id": "C7",
    "name": "PM SVANidhi",
    "name_te": "పీఎం స్వనిధి",
    "name_hi": "पीएम स्वनिधि",
    "category": "Loan",
    "priority": "medium",
    "target_keywords": ["street vendor", "small loan", "business", "వీధి వ్యాపారులు", "అప్పు", "thela"],
    "benefit": "Loan ₹10,000–₹50,000",
    "benefit_te": "వీధి వ్యాపారులకు 10 పది (padi) వేల నుండి 50 యాభై (yabhai) వేల వరకు రుణం",
    "benefit_hi": "रेहड़ी-पटरी वालों के लिए ₹10,000 से ₹50,000 तक का ऋण",
    "docs": ["Vendor ID", "Aadhaar", "Bank Account"],
    "docs_te": ["వ్యాపారి గుర్తింపు కార్డు", "ఆధార్ కార్డు", "బ్యాంక్ ఖాతా"],
    "docs_hi": ["विक्रेता आईडी", "आधार कार्ड", "बैंक खाता"],
    "apply_at": "Bank or Municipal Office",
    "apply_at_te": "బ్యాంకు లేదా మున్సిపల్ కార్యాలయం",
    "apply_at_hi": "बैंक या नगर पालिका कार्यालय",
    "map_search": "Municipal office near me",
    "missing_doc_help_te": "మున్సిపాలిటీ ఇచ్చిన వెండింగ్ సర్టిఫికేట్ తప్పనిసరి.",
    "missing_doc_help_hi": "नगर पालिका द्वारा जारी वेंडिंग प्रमाण पत्र अनिवार्य है।",
    "icon": "storefront",
    "eligibility_ineligible": "Non-street vendors, those without ULB ID",
    "fine_print": "Collateral-free loan. Interest subsidy on timely repayment."
  },
  {
    "id": "C8",
    "name": "PM Matru Vandana",
    "name_te": "పీఎం మాతృ వందన",
    "name_hi": "पीएम मातृ वंदना",
    "category": "Health",
    "priority": "medium",
    "target_keywords": ["pregnant", "delivery", "mother", "గర్భిణీ", "తల్లి", "bachcha"],
    "benefit": "₹5,000 for first pregnancy",
    "benefit_te": "మొదటి కాన్పు కోసం 5 ఐదు (aidhu) వేల రూపాయల ఆర్థిక సాయం",
    "benefit_hi": "पहली गर्भावस्था के लिए ₹5,000 की सहायता",
    "docs": ["MCP Card", "Aadhaar", "Bank Passbook"],
    "docs_te": ["తల్లి పిల్లల కార్డు", "ఆధార్ కార్డు", "బ్యాంక్ పాస్బుక్"],
    "docs_hi": ["एमसीपी कार्ड", "आधार कार्ड", "बैंक पासबुक"],
    "apply_at": "Anganwadi Center",
    "apply_at_te": "అంగన్వాడీ కేంద్రం",
    "apply_at_hi": "आंगनवाड़ी केंद्र",
    "map_search": "Anganwadi center near me",
    "missing_doc_help_te": "అంగన్వాడీలో మీ పేరు నమోదు చేయించుకొని MCP కార్డు పొందండి.",
    "missing_doc_help_hi": "आंगनवाड़ी में अपना नाम दर्ज कराएं और एमसीपी कार्ड प्राप्त करें।",
    "icon": "pregnant_woman",
    "eligibility_ineligible": "Govt employees, second or later pregnancy (except specific cases)",
    "fine_print": "Amount paid in installments linked to check-ups and immunization."
  },
  {
    "id": "C9",
    "name": "Atal Pension Yojana",
    "name_te": "అటల్ పెన్షన్ యోజన",
    "name_hi": "अटल पेंशन योजना",
    "category": "Pension",
    "priority": "medium",
    "target_keywords": ["pension", "old age", "savings", "పెన్షన్", "పొదుపు", "budhapa"],
    "benefit": "₹1,000–₹5,000/mo pension",
    "benefit_te": "60 ఏళ్ళ తర్వాత నెలకు 1 ఒక (oka) వేయి నుండి 5 ఐదు (aidhu) వేల వరకు పెన్షన్",
    "benefit_hi": "60 वर्ष की आयु के बाद ₹1,000 से ₹5,000 मासिक पेंशन",
    "docs": ["Aadhaar", "Bank Account"],
    "docs_te": ["ఆధార్ కార్డు", "బ్యాంక్ ఖాతా"],
    "docs_hi": ["आधार कार्ड", "बैंक खाता"],
    "apply_at": "Bank Branch",
    "apply_at_te": "మీ బ్యాంకులో",
    "apply_at_hi": "अपने बैंक में",
    "map_search": "bank near me",
    "missing_doc_help_te": "18 నుండి 40 ఏళ్ళ లోపు వారు మాత్రమే ఇందులో చేరవచ్చు.",
    "missing_doc_help_hi": "केवल 18 से 40 वर्ष की आयु के लोग ही शामिल हो सकते हैं।",
    "icon": "payments",
    "eligibility_ineligible": "People > 40 yrs, income tax payers, EPF/NPS members",
    "fine_print": "Monthly contribution depends on entry age. Govt matches contribution for some."
  },
  {
    "id": "C10",
    "name": "PM Garib Kalyan",
    "name_te": "పీఎం గరీబ్ కళ్యాణ్",
    "name_hi": "पीएम गरीब कल्याण",
    "category": "Utility",
    "priority": "high",
    "target_keywords": ["free rice", "ration", "food", "ఉచిత బియ్యం", "రేషన్", "khana"],
    "benefit": "Free 5 kg food grains/person",
    "benefit_te": "ప్రతి వ్యక్తికి నెలకు 5 ఐదు (aidhu) కేజీల ఉచిత బియ్యం",
    "benefit_hi": "प्रति व्यक्ति 5 पांच (paanch) किलो मुफ्त अनाज",
    "docs": ["Ration Card"],
    "docs_te": ["రేషన్ కార్డు"],
    "docs_hi": ["राशन कार्ड"],
    "apply_at": "Nearest Ration Shop",
    "apply_at_te": "రేషన్ షాపులో",
    "apply_at_hi": "राशन की दुकान पर",
    "map_search": "Ration shop near me",
    "missing_doc_help_te": "మీ రేషన్ కార్డు ఆధార్ తో లింక్ అయి ఉండాలి.",
    "missing_doc_help_hi": "आपका राशन कार्ड आधार से लिंक होना चाहिए।",
    "icon": "shopping_basket",
    "eligibility_ineligible": "Non-ration card holders, APL families in some regions",
    "fine_print": "Additional free grains over and above regular NFSA ration."
  },
  {
    "id": "C11",
    "name": "Stand-Up India",
    "name_te": "స్టాండ్-అప్ ఇండియా",
    "name_hi": "स्टैंड-अप इंडिया",
    "category": "Business",
    "priority": "low",
    "target_keywords": ["business loan", "sc st loan", "women business", "వ్యాపార రుణం", "startup"],
    "benefit": "₹10L to ₹1Cr business loan",
    "benefit_te": "వ్యాపారం కోసం 10 పది (padi) లక్షల నుండి 1 ఒక (oka) కోటి వరకు అప్పు",
    "benefit_hi": "व्यापार के लिए ₹10 लाख से ₹1 करोड़ तक का ऋण",
    "docs": ["Project Report", "Aadhaar", "Caste Cert"],
    "docs_te": ["ప్రాజెక్ట్ రిపోర్ట్", "ఆధార్ కార్డు", "కుల ధృవీకరణ"],
    "docs_hi": ["प्रोजेक्ट रिपोर्ट", "आधार कार्ड", "जाति प्रमाण पत्र"],
    "apply_at": "Bank Branch",
    "apply_at_te": "ఏదైనా బ్యాంకులో",
    "apply_at_hi": "किसी भी बैंक में",
    "map_search": "bank near me",
    "missing_doc_help_te": "ఇది కేవలం ఎస్సీ, ఎస్టీ మరియు మహిళా పారిశ్రామికవేత్తలకు మాత్రమే.",
    "missing_doc_help_hi": "यह केवल एससी, एसटी और महिला उद्यमियों के लिए है।",
    "icon": "trending_up",
    "eligibility_ineligible": "Non-SC/ST/Women, existing large businesses, defaulters",
    "fine_print": "Loan for greenfield enterprises. At least one SC/ST or woman borrower per branch."
  },
  {
    "id": "C12",
    "name": "E-Shram",
    "name_te": "ఈ-శ్రమ్ కార్డు",
    "name_hi": "ई-श्रम कार्ड",
    "category": "Insurance",
    "priority": "high",
    "target_keywords": ["worker card", "unorganized", "accident cover", "కూలి", "కార్మికుడు", "labour"],
    "benefit": "Social security + 2L accident cover",
    "benefit_te": "ప్రమాద బీమా మరియు ప్రభుత్వ సాయం",
    "benefit_hi": "दुर्घटना बीमा और सरकारी सहायता",
    "docs": ["Aadhaar", "Bank Account"],
    "docs_te": ["ఆధార్ కార్డు", "బ్యాంక్ పాస్బుక్"],
    "docs_hi": ["आधार कार्ड", "बैंक पासबुक"],
    "apply_at": "CSC Center",
    "apply_at_te": "సి.ఎస్.సి (CSC) లేదా మీసేవ కేంద్రం",
    "apply_at_hi": "सीएससी या मीसेवा केंद्र",
    "map_search": "CSC center near me",
    "missing_doc_help_te": "కార్డు వచ్చిన తర్వాత బ్యాంకులో 20 ఇరవై (iravai) రూపాయలు కట్టి బీమా చేసుకోవాలి.",
    "missing_doc_help_hi": "कार्ड मिलने के बाद बैंक में 20 बीस (bees) रुपये जमा कर बीमा करवाना होगा।",
    "icon": "badge",
    "eligibility_ineligible": "Organized sector workers (EPF/ESIC), govt employees, tax payers",
    "fine_print": "Registration alone doesn't give insurance. Must pay ₹12/year for PMSBY."
  },
  {
    "id": "C13",
    "name": "Lakhpati Didi",
    "name_te": "లఖ్ పతి దీదీ",
    "name_hi": "लखपति दीदी",
    "category": "Business",
    "priority": "medium",
    "target_keywords": ["shg", "women group", "loan", "మహిళా సంఘం", "డ్వాక్రా", "samuh"],
    "benefit": "Skill training + loans for SHG women",
    "benefit_te": "మహిళా సంఘం సభ్యులకు శిక్షణ మరియు అప్పు",
    "benefit_hi": "स्वयं सहायता समूह की महिलाओं के लिए प्रशिक्षण और ऋण",
    "docs": ["SHG ID", "Aadhaar"],
    "docs_te": ["సంఘం గుర్తింపు కార్డు", "ఆధార్ కార్డు"],
    "docs_hi": ["समूह आईडी", "आधार कार्ड"],
    "apply_at": "Village Organization / SRLM Office",
    "apply_at_te": "గ్రామ సమాఖ్య లేదా సంఘం కార్యాలయం",
    "apply_at_hi": "ग्राम संगठन या एसआरएलएम कार्यालय",
    "map_search": "SERP office near me",
    "missing_doc_help_te": "మీరు ఏదైనా స్వయం సహాయక సంఘం (SHG) లో సభ్యురాలిగా ఉండాలి.",
    "missing_doc_help_hi": "आपको किसी स्वयं सहायता समूह (SHG) का सदस्य होना चाहिए।",
    "icon": "groups",
    "eligibility_ineligible": "Non-SHG women, men",
    "fine_print": "Aims to help women earn at least ₹1 lakh per year through small businesses."
  },
  {
    "id": "C14",
    "name": "PM Surya Ghar",
    "name_te": "పీఎం సూర్య ఘర్",
    "name_hi": "पीएम सूर्य घर",
    "category": "Utility",
    "priority": "medium",
    "target_keywords": ["solar panel", "free current", "subsidy", "సౌర శక్తి", "కరెంటు సబ్సిడీ", "dhup"],
    "benefit": "₹78,000 subsidy for solar panels",
    "benefit_te": "ఇంటిపై సోలార్ ప్లేట్ల కోసం 78 డెబ్బై ఎనిమిది (debbai enimidi) వేల వరకు సాయం",
    "benefit_hi": "सोलर पैनल के लिए ₹78,000 तक की सब्सिडी",
    "docs": ["Electricity Bill", "Aadhaar", "Roof Photo"],
    "docs_te": ["కరెంటు బిల్లు", "ఆధార్ కార్డు", "ఇంటి ఫోటో"],
    "docs_hi": ["बिजली बिल", "आधार कार्ड", "छत की फोटो"],
    "apply_at": "DISCOM or Online Portal",
    "apply_at_te": "విద్యుత్ కార్యాలయం లేదా ఆన్లైన్ లో",
    "apply_at_hi": "बिजली विभाग या ऑनलाइन पोर्टल",
    "map_search": "Electricity office near me",
    "missing_doc_help_te": "మీకు సొంత ఇల్లు మరియు ఖాళీ పైకప్పు ఉండాలి.",
    "missing_doc_help_hi": "आपके पास अपना घर और खाली छत होनी चाहिए।",
    "icon": "solar_power",
    "eligibility_ineligible": "Commercial buildings, houses without clear roof access, existing solar users",
    "fine_print": "Subsidy directly to bank account. Apply at pmsuryaghar.gov.in."
  },
  {
    "id": "C15",
    "name": "Jan Aushadhi",
    "name_te": "జన ఔషధి",
    "name_hi": "जन औषधि",
    "category": "Health",
    "priority": "medium",
    "target_keywords": ["medicine", "cheap tablet", "medical shop", "మందులు", "తక్కువ ధర", "dawai"],
    "benefit": "Up to 90% discount on medicines",
    "benefit_te": "మందుల ధరలపై 90 తొంభై (thombai) శాతం వరకు తగ్గింపు",
    "benefit_hi": "दवाइयों पर 90 नब्बे (nabbe) प्रतिशत तक की छूट",
    "docs": ["Doctor Prescription"],
    "docs_te": ["డాక్టర్ రాసిన మందుల చీటీ"],
    "docs_hi": ["डॉक्टर का पर्चा"],
    "apply_at": "Jan Aushadhi Kendra",
    "apply_at_te": "ప్రభుత్వ జన ఔషధి కేంద్రం",
    "apply_at_hi": "सरकारी जन औषधि केंद्र",
    "map_search": "Jan Aushadhi store near me",
    "missing_doc_help_te": "అన్ని రకాల ఇంగ్లీష్ మందులు ఇక్కడ తక్కువ ధరకు దొరుకుతాయి.",
    "missing_doc_help_hi": "यहां सभी अंग्रेजी दवाइयां कम कीमत पर उपलब्ध हैं।",
    "icon": "medication",
    "eligibility_ineligible": "Open to all citizens — no restrictions",
    "fine_print": "Show prescription at store. Over 9,000 medicines available."
  },
  {
    "id": "C16",
    "name": "PM Mudra Yojana",
    "name_te": "పీఎం ముద్ర యోజన",
    "name_hi": "पीएम मुद्रा योजना",
    "category": "Loan",
    "priority": "medium",
    "target_keywords": ["business loan", "small shop", "loan", "చిన్న వ్యాపారం", "అప్పు", "karz"],
    "benefit": "Micro loans up to ₹10L",
    "benefit_te": "చిన్న వ్యాపారాల కోసం 10 పది (padi) లక్షల వరకు రుణం",
    "benefit_hi": "छोटे व्यवसायों के लिए ₹10 लाख तक का ऋण",
    "docs": ["Business Plan", "Aadhaar", "Bank Statment"],
    "docs_te": ["వ్యాపార ప్రణాళిక", "ఆధార్ కార్డు", "బ్యాంక్ వివరాలు"],
    "docs_hi": ["व्यापार योजना", "आधार कार्ड", "बैंक विवरण"],
    "apply_at": "Any Bank",
    "apply_at_te": "ఏదైనా బ్యాంకులో",
    "apply_at_hi": "किसी भी बैंक में",
    "map_search": "bank near me",
    "missing_doc_help_te": "షూరిటీ లేకుండానే ఈ అప్పు పొందవచ్చు.",
    "missing_doc_help_hi": "बिना गारंटी के यह ऋण लिया जा सकता है।",
    "icon": "account_balance",
    "eligibility_ineligible": "Salaried employees, farming loans, existing defaulters",
    "fine_print": "3 categories: Shishu (up to 50k), Kishor (50k-5L), Tarun (5L-10L)."
  },
  {
    "id": "C17",
    "name": "PM PRANAM",
    "name_te": "పీఎం ప్రణామ్",
    "name_hi": "पीएम प्रणाम",
    "category": "Agriculture",
    "priority": "low",
    "target_keywords": ["organic farm", "fertilizer", "bio", "సేంద్రియ ఎరువులు", "మందులు", "khaad"],
    "benefit": "Bio-fertilizer subsidy",
    "benefit_te": "సేంద్రియ ఎరువులు వాడే రైతులకు ప్రోత్సాహం",
    "benefit_hi": "जैविक खाद का उपयोग करने वाले किसानों को प्रोत्साहन",
    "docs": ["Kisan ID", "Aadhaar"],
    "docs_te": ["రైతు పాస్బుక్", "ఆధార్ కార్డు"],
    "docs_hi": ["किसान पासबुक", "आधार कार्ड"],
    "apply_at": "Agriculture Department",
    "apply_at_te": "వ్యవసాయ శాఖ కార్యాలయం",
    "apply_at_hi": "कृषि विभाग",
    "map_search": "Agriculture office near me",
    "missing_doc_help_te": "రసాయన ఎరువుల వాడకం తగ్గించే రైతులకు ఇది మేలు చేస్తుంది.",
    "missing_doc_help_hi": "यह उन किसानों के लिए है जो रासायनिक खाद का उपयोग कम करते हैं।",
    "icon": "eco",
    "eligibility_ineligible": "Farmers using only chemical fertilizers, non-farmers",
    "fine_print": "Govt saves money on chemical subsidies and passes benefit to organic farming."
  },
  {
    "id": "C18",
    "name": "BOCW Welfare",
    "name_te": "భవన నిర్మాణ కార్మిక సాయం",
    "name_hi": "भवन निर्माण श्रमिक कल्याण",
    "category": "Social",
    "priority": "medium",
    "target_keywords": ["construction worker", "labour card", "కూలి", "మేస్త్రీ", "majdoor"],
    "benefit": "Scholarships, tools, medical help",
    "benefit_te": "కార్మికులకు పనిముట్లు, పిల్లలకు చదువు సాయం",
    "benefit_hi": "श्रमिकों के लिए औजार और बच्चों के लिए छात्रवृत्ति",
    "docs": ["Labour Card", "Aadhaar"],
    "docs_te": ["లేబర్ కార్డు", "ఆధార్ కార్డు"],
    "docs_hi": ["लेबर कार्ड", "आधार कार्ड"],
    "apply_at": "State Labour Office",
    "apply_at_te": "కార్మిక శాఖ కార్యాలయం",
    "apply_at_hi": "श्रम विभाग कार्यालय",
    "map_search": "Labour office near me",
    "missing_doc_help_te": "మీరు ఏటా లేబర్ కార్డును పునరుద్ధరించుకోవాలి.",
    "missing_doc_help_hi": "आपको हर साल लेबर कार्ड रिन्यू करवाना होगा।",
    "icon": "engineering",
    "eligibility_ineligible": "Workers with < 90 days of construction work, non-construction workers",
    "fine_print": "Must be registered with State Labour Board to get benefits."
  },
  {
    "id": "C19",
    "name": "One Nation One Ration",
    "name_te": "వన్ నేషన్ వన్ రేషన్",
    "name_hi": "वन नेशन वन राशन",
    "category": "Utility",
    "priority": "medium",
    "target_keywords": ["ration anywhere", "migrant", "బియ్యం", "వలస", "pravasi"],
    "benefit": "Access ration anywhere in India",
    "benefit_te": "దేశంలో ఎక్కడైనా మీ రేషన్ కార్డుతో బియ్యం తీసుకోవచ్చు",
    "benefit_hi": "देश में कहीं भी अपने राशन कार्ड से अनाज लें",
    "docs": ["Aadhaar-linked Ration Card"],
    "docs_te": ["ఆధార్ తో లింక్ అయిన రేషన్ కార్డు"],
    "docs_hi": ["आधार लिंक राशन कार्ड"],
    "apply_at": "Any Fair Price Shop",
    "apply_at_te": "ఏ రేషన్ షాపులోనైనా",
    "apply_at_hi": "किसी भी राशन की दुकान पर",
    "map_search": "Ration shop near me",
    "missing_doc_help_te": "వలస వెళ్లే కార్మికులకు ఇది చాలా ఉపయోగకరం.",
    "missing_doc_help_hi": "प्रवासी मजदूरों के लिए यह बहुत उपयोगी है।",
    "icon": "location_on",
    "eligibility_ineligible": "No ration card, non-linked card",
    "fine_print": "Portability feature. Use existing card nationwide. Aadhaar linking mandatory."
  },
  {
    "id": "C20",
    "name": "PM JJBY",
    "name_te": "జీవన జ్యోతి బీమా",
    "name_hi": "जीवन ज्योति बीमा",
    "category": "Insurance",
    "priority": "medium",
    "target_keywords": ["life insurance", "bank bima", "చనిపోతే", "బీమా", "mrityu"],
    "benefit": "₹2L life insurance for ₹436/yr",
    "benefit_te": "ఏడాదికి 436 రూపాయలకే 2 రెండు (rendu) లక్షల జీవిత బీమా",
    "benefit_hi": "साल में ₹436 में 2 दो (do) लाख का जीवन बीमा",
    "docs": ["Bank Account", "Aadhaar"],
    "docs_te": ["బ్యాంక్ ఖాతా", "ఆధార్ కార్డు"],
    "docs_hi": ["बैंक खाता", "आधार कार्ड"],
    "apply_at": "Bank Branch",
    "apply_at_te": "మీ బ్యాంకులో",
    "apply_at_hi": "अपने बैंक में",
    "map_search": "bank near me",
    "missing_doc_help_te": "ఏ కారణం చేతనైనా చనిపోతే కుటుంబానికి సాయం అందుతుంది.",
    "missing_doc_help_hi": "किसी भी कारण से मृत्यु होने पर परिवार को सहायता मिलती है।",
    "icon": "volunteer_activism",
    "eligibility_ineligible": "Aged < 18 or > 55, no bank account",
    "fine_print": "Premium auto-debited annually. Covers death due to any reason."
  },
  {
    "id": "C21",
    "name": "PM PMSBY",
    "name_te": "ప్రమాద బీమా యోజన",
    "name_hi": "सुरक्षा बीमा योजना",
    "category": "Insurance",
    "priority": "medium",
    "target_keywords": ["accident insurance", "20 rupees", "death cover", "ప్రమాద బీమా", "తక్కువ ఖర్చు", "bima"],
    "benefit": "₹2L accident cover for ₹20/yr",
    "benefit_te": "ఏడాదికి కేవలం 20 ఇరవై (iravai) రూపాయలకే 2 రెండు (rendu) లక్షల ప్రమాద బీమా",
    "benefit_hi": "साल में सिर्फ 20 बीस (bees) रुपये में 2 दो (do) लाख का दुर्घटना बीमा",
    "docs": ["Bank Account", "Aadhaar"],
    "docs_te": ["బ్యాంక్ ఖాతా", "ఆధార్ కార్డు"],
    "docs_hi": ["बैंक खाता", "आधार कार्ड"],
    "apply_at": "Your Bank Branch",
    "apply_at_te": "మీరు ఖాతా ఉన్న బ్యాంకులో",
    "apply_at_hi": "अपने बैंक की शाखा में",
    "map_search": "bank near me",
    "missing_doc_help_te": "మీ బ్యాంకులో ఒక ఫారం నింపి సంతకం పెడితే సరిపోతుంది.",
    "missing_doc_help_hi": "अपने बैंक में एक फॉर्म भरकर जमा करना काफी है।",
    "icon": "shield",
    "eligibility_ineligible": "People below 18 or above 70, no bank account",
    "fine_print": "Only for accidents. Different from PMJJBY life cover."
  },
  {
    "id": "C22",
    "name": "National Disability Pension",
    "name_te": "దివ్యాంగుల పెన్షన్",
    "name_hi": "दिव्यांग पेंशन",
    "category": "Pension",
    "priority": "high",
    "target_keywords": ["disabled", "handicap", "pension", "వికలాంగులు", "పెన్షన్", "divyang"],
    "benefit": "Monthly pension for disability",
    "benefit_te": "దివ్యాంగులకు ప్రతి నెలా పెన్షన్ సాయం",
    "benefit_hi": "विकलांग नागरिकों के लिए मासिक पेंशन",
    "docs": ["Disability Cert", "Aadhaar"],
    "docs_te": ["సదరం సర్టిఫికేట్", "ఆధార్ కార్డు"],
    "docs_hi": ["विकलांगता प्रमाण पत्र", "आधार कार्ड"],
    "apply_at": "CSC or Social Welfare Office",
    "apply_at_te": "మీసేవ లేదా సాంఘిక సంక్షేమ కార్యాలయం",
    "apply_at_hi": "सीएससी या समाज कल्याण कार्यालय",
    "map_search": "Social welfare office near me",
    "missing_doc_help_te": "తెలంగాణలో దీనికి చేయూత ద్వారా 6 ఆరు (aaru) వేలు అందుతాయి.",
    "missing_doc_help_hi": "तेलंगाना में इसके तहत ₹6,000 मिलते हैं।",
    "icon": "accessible",
    "eligibility_ineligible": "< 40% disability, regular income, other pensions",
    "fine_print": "Amount varies by state. Disability certificate must be verified."
  },
  {
    "id": "C23",
    "name": "National Widow Pension",
    "name_te": "విధవ పెన్షన్",
    "name_hi": "विधवा पेंशन",
    "category": "Pension",
    "priority": "high",
    "target_keywords": ["widow", "pension", "husband death", "విధవ", "పెన్షన్", "vidhwa"],
    "benefit": "Monthly pension for widows",
    "benefit_te": "భర్త చనిపోయిన మహిళలకు నెలవారీ పెన్షన్",
    "benefit_hi": "विधवा महिलाओं के लिए मासिक पेंशन",
    "docs": ["Death Certificate", "Aadhaar"],
    "docs_te": ["భర్త మరణ ధృవీకరణ", "ఆధార్ కార్డు"],
    "docs_hi": ["मृत्यु प्रमाण पत्र", "आधार कार्ड"],
    "apply_at": "Gram Panchayat",
    "apply_at_te": "గ్రామ పంచాయతీ కార్యాలయం",
    "apply_at_hi": "ग्राम पंचायत कार्यालय",
    "map_search": "Gram Panchayat near me",
    "missing_doc_help_te": "తెలంగాణలో దీని ద్వారా 4 నాలుగు (nalugu) వేల పెన్షన్ వస్తుంది.",
    "missing_doc_help_hi": "तेलंगाना में इसके तहत ₹4,000 पेंशन मिलती है।",
    "icon": "person_remove",
    "eligibility_ineligible": "Remarried widows, regular income, non-BPL",
    "fine_print": "Covered under Cheyutha in Telangana at higher rates."
  },
  {
    "id": "C24",
    "name": "PM Daksh",
    "name_te": "పీఎం దక్ష",
    "name_hi": "पीएम दक्ष",
    "category": "Education",
    "priority": "low",
    "target_keywords": ["skill training", "free course", "job", "శిక్షణ", "ఉపాధి", "kaushal"],
    "benefit": "Free skill training + stipend",
    "benefit_te": "ఉచిత వృత్తి శిక్షణ మరియు నెలకు స్టైఫండ్",
    "benefit_hi": "मुफ्त कौशल प्रशिक्षण और वजीफा",
    "docs": ["Caste Certificate", "Aadhaar"],
    "docs_te": ["కుల ధృవీకరణ", "ఆధార్ కార్డు"],
    "docs_hi": ["जाति प्रमाण पत्र", "आधार कार्ड"],
    "apply_at": "Nearest Training Centre",
    "apply_at_te": "దగ్గరలోని శిక్షణ కేంద్రం",
    "apply_at_hi": "नजदीकी प्रशिक्षण केंद्र",
    "map_search": "Skill development center near me",
    "missing_doc_help_te": "శిక్షణ సమయంలో మీకు నెలవారీ ఖర్చుల కోసం డబ్బులు ఇస్తారు.",
    "missing_doc_help_hi": "प्रशिक्षण के दौरान वजीफा भी दिया जाता है।",
    "icon": "model_training",
    "eligibility_ineligible": "General category youth (non-minority), aged > 45",
    "fine_print": "Focus on SC/ST/OBC and marginalized groups. Courses in IT, hospitality, etc."
  },
  {
    "id": "C25",
    "name": "PM Awas Yojana Urban",
    "name_te": "పీఎం ఆవాస్ యోజన (పట్టణ)",
    "name_hi": "पीएम आवास योजना (शहरी)",
    "category": "Housing",
    "priority": "medium",
    "target_keywords": ["urban house", "flat", "city home", "పట్టణ ఇల్లు", "నిర్మాణం", "shahar"],
    "benefit": "Housing subsidy for urban poor",
    "benefit_te": "పట్టణాల్లో ఇల్లు కట్టుకోవడానికి ఆర్థిక సాయం",
    "benefit_hi": "शहरी गरीबों के लिए आवास सब्सिडी",
    "docs": ["Income Certificate", "Aadhaar"],
    "docs_te": ["ఆదాయ ధృవీకరణ", "ఆధార్ కార్డు"],
    "docs_hi": ["आय प्रमाण पत्र", "आधार कार्ड"],
    "apply_at": "Municipal Corporation",
    "apply_at_te": "మున్సిపల్ కార్యాలయం",
    "apply_at_hi": "नगर निगम कार्यालय",
    "map_search": "Municipal corporation near me",
    "missing_doc_help_te": "మీకు దేశంలో ఎక్కడా సొంత ఇల్లు ఉండకూడదు.",
    "missing_doc_help_hi": "आपके पास देश में कहीं भी अपना पक्का घर नहीं होना चाहिए।",
    "icon": "location_city",
    "eligibility_ineligible": "Owners of pucca house, income > ₹18L/yr",
    "fine_print": "4 components including credit-linked subsidy for different income groups."
  }
];

// Added by AI Agent - Database updated today, March 30, 2026.
